sudo: required
dist: xenial

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix js
  # - lix run travix flash
  - lix run travix java
  - if [[ "$(haxe -version)" =~ ^4.* ]]; then lix run travix java -D jvm; fi
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php